spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
    
  jpa:
  # defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate: 
        format_sql: true
        show_sql: true
        
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 1000
        
logging.level:
  org.hibernate.SQL: debug # 로그파일로 떨어짐
# org.hibernate.type: trace # 파라미터 까지 볼수있는 로그 옵션